#construye la imagen para crear los contenedores de las instancias
FROM mysql

ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update
RUN apt upgrade -y

RUN apt install nodejs npm -y

RUN npm install pm2 -g

RUN mkdir lab3
WORKDIR /home/lab3
RUN git clone --branch main https://github.com/drox13/SD-lab3-instancia.git

WORKDIR /home/lab3/SD-lab2-instancia
RUN npm install

EXPOSE 4000
CMD ["pm2-runtime", "index.js"]